"""autogenerated by genpy from monstertruck_msgs/MotionCommand.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class MotionCommand(genpy.Message):
  _md5sum = "c7315886ba784873a03b26d185e1ab17"
  _type = "monstertruck_msgs/MotionCommand"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 speed
float32 steerAngleFront
float32 steerAngleRear
bool brake

"""
  __slots__ = ['speed','steerAngleFront','steerAngleRear','brake']
  _slot_types = ['float32','float32','float32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       speed,steerAngleFront,steerAngleRear,brake

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MotionCommand, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.speed is None:
        self.speed = 0.
      if self.steerAngleFront is None:
        self.steerAngleFront = 0.
      if self.steerAngleRear is None:
        self.steerAngleRear = 0.
      if self.brake is None:
        self.brake = False
    else:
      self.speed = 0.
      self.steerAngleFront = 0.
      self.steerAngleRear = 0.
      self.brake = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3fB.pack(_x.speed, _x.steerAngleFront, _x.steerAngleRear, _x.brake))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.speed, _x.steerAngleFront, _x.steerAngleRear, _x.brake,) = _struct_3fB.unpack(str[start:end])
      self.brake = bool(self.brake)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3fB.pack(_x.speed, _x.steerAngleFront, _x.steerAngleRear, _x.brake))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.speed, _x.steerAngleFront, _x.steerAngleRear, _x.brake,) = _struct_3fB.unpack(str[start:end])
      self.brake = bool(self.brake)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3fB = struct.Struct("<3fB")
