"""autogenerated by genpy from monstertruck_msgs/ServoPositions.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import monstertruck_msgs.msg

class ServoPositions(genpy.Message):
  _md5sum = "58f4f4c70dfb67bb7c1c5f32abf2a35a"
  _type = "monstertruck_msgs/ServoPositions"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """ServoPosition[] servo

================================================================================
MSG: monstertruck_msgs/ServoPosition
uint8 id
float32 position

"""
  __slots__ = ['servo']
  _slot_types = ['monstertruck_msgs/ServoPosition[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       servo

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ServoPositions, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.servo is None:
        self.servo = []
    else:
      self.servo = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.servo)
      buff.write(_struct_I.pack(length))
      for val1 in self.servo:
        _x = val1
        buff.write(_struct_Bf.pack(_x.id, _x.position))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.servo is None:
        self.servo = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.servo = []
      for i in range(0, length):
        val1 = monstertruck_msgs.msg.ServoPosition()
        _x = val1
        start = end
        end += 5
        (_x.id, _x.position,) = _struct_Bf.unpack(str[start:end])
        self.servo.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.servo)
      buff.write(_struct_I.pack(length))
      for val1 in self.servo:
        _x = val1
        buff.write(_struct_Bf.pack(_x.id, _x.position))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.servo is None:
        self.servo = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.servo = []
      for i in range(0, length):
        val1 = monstertruck_msgs.msg.ServoPosition()
        _x = val1
        start = end
        end += 5
        (_x.id, _x.position,) = _struct_Bf.unpack(str[start:end])
        self.servo.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_Bf = struct.Struct("<Bf")
