/* Auto-generated by genmsg_cpp for file /home/kohlbrecher/hector/indigo/stacks/hector/monstertruck/monstertruck_msgs/msg/ServoCommand.msg */
#ifndef MONSTERTRUCK_MSGS_MESSAGE_SERVOCOMMAND_H
#define MONSTERTRUCK_MSGS_MESSAGE_SERVOCOMMAND_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace monstertruck_msgs
{
template <class ContainerAllocator>
struct ServoCommand_ {
  typedef ServoCommand_<ContainerAllocator> Type;

  ServoCommand_()
  : id(0)
  , position(0.0)
  {
  }

  ServoCommand_(const ContainerAllocator& _alloc)
  : id(0)
  , position(0.0)
  {
  }

  typedef uint8_t _id_type;
  uint8_t id;

  typedef float _position_type;
  float position;

  static const float DISABLE;

  typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommand_<ContainerAllocator>  const> ConstPtr;
}; // struct ServoCommand
typedef  ::monstertruck_msgs::ServoCommand_<std::allocator<void> > ServoCommand;

typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommand> ServoCommandPtr;
typedef boost::shared_ptr< ::monstertruck_msgs::ServoCommand const> ServoCommandConstPtr;

template<typename ContainerAllocator> const float ServoCommand_<ContainerAllocator>::DISABLE = 999.0;

template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::monstertruck_msgs::ServoCommand_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace monstertruck_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::monstertruck_msgs::ServoCommand_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "7b8ae92b8ba5e2ca96969db3b6b4d5fc";
  }

  static const char* value(const  ::monstertruck_msgs::ServoCommand_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x7b8ae92b8ba5e2caULL;
  static const uint64_t static_value2 = 0x96969db3b6b4d5fcULL;
};

template<class ContainerAllocator>
struct DataType< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "monstertruck_msgs/ServoCommand";
  }

  static const char* value(const  ::monstertruck_msgs::ServoCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint8 id\n\
float32 position\n\
float32 DISABLE = 999.0\n\
\n\
";
  }

  static const char* value(const  ::monstertruck_msgs::ServoCommand_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.id);
    stream.next(m.position);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ServoCommand_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::monstertruck_msgs::ServoCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::monstertruck_msgs::ServoCommand_<ContainerAllocator> & v) 
  {
    s << indent << "id: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.id);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
  }
};


} // namespace message_operations
} // namespace ros

#endif // MONSTERTRUCK_MSGS_MESSAGE_SERVOCOMMAND_H

