/* Auto-generated by genmsg_cpp for file /home/kohlbrecher/hector/indigo/stacks/hector/monstertruck/monstertruck_msgs/srv/GetGazeDirection.srv */
#ifndef MONSTERTRUCK_MSGS_SERVICE_GETGAZEDIRECTION_H
#define MONSTERTRUCK_MSGS_SERVICE_GETGAZEDIRECTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"



#include "geometry_msgs/PointStamped.h"

namespace monstertruck_msgs
{
template <class ContainerAllocator>
struct GetGazeDirectionRequest_ {
  typedef GetGazeDirectionRequest_<ContainerAllocator> Type;

  GetGazeDirectionRequest_()
  : stamp()
  {
  }

  GetGazeDirectionRequest_(const ContainerAllocator& _alloc)
  : stamp()
  {
  }

  typedef ros::Time _stamp_type;
  ros::Time stamp;


  typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator>  const> ConstPtr;
}; // struct GetGazeDirectionRequest
typedef  ::monstertruck_msgs::GetGazeDirectionRequest_<std::allocator<void> > GetGazeDirectionRequest;

typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionRequest> GetGazeDirectionRequestPtr;
typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionRequest const> GetGazeDirectionRequestConstPtr;



template <class ContainerAllocator>
struct GetGazeDirectionResponse_ {
  typedef GetGazeDirectionResponse_<ContainerAllocator> Type;

  GetGazeDirectionResponse_()
  : pointOut()
  {
  }

  GetGazeDirectionResponse_(const ContainerAllocator& _alloc)
  : pointOut(_alloc)
  {
  }

  typedef  ::geometry_msgs::PointStamped_<ContainerAllocator>  _pointOut_type;
   ::geometry_msgs::PointStamped_<ContainerAllocator>  pointOut;


  typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator>  const> ConstPtr;
}; // struct GetGazeDirectionResponse
typedef  ::monstertruck_msgs::GetGazeDirectionResponse_<std::allocator<void> > GetGazeDirectionResponse;

typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionResponse> GetGazeDirectionResponsePtr;
typedef boost::shared_ptr< ::monstertruck_msgs::GetGazeDirectionResponse const> GetGazeDirectionResponseConstPtr;


struct GetGazeDirection
{

typedef GetGazeDirectionRequest Request;
typedef GetGazeDirectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct GetGazeDirection
} // namespace monstertruck_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "84d365d08d5fc49dde870daba1c7992c";
  }

  static const char* value(const  ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x84d365d08d5fc49dULL;
  static const uint64_t static_value2 = 0xde870daba1c7992cULL;
};

template<class ContainerAllocator>
struct DataType< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "monstertruck_msgs/GetGazeDirectionRequest";
  }

  static const char* value(const  ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
\n\
time stamp\n\
\n\
\n\
";
  }

  static const char* value(const  ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "575e2bfcd2844c893c892df880361661";
  }

  static const char* value(const  ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x575e2bfcd2844c89ULL;
  static const uint64_t static_value2 = 0x3c892df880361661ULL;
};

template<class ContainerAllocator>
struct DataType< ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "monstertruck_msgs/GetGazeDirectionResponse";
  }

  static const char* value(const  ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "\n\
geometry_msgs/PointStamped pointOut\n\
\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PointStamped\n\
# This represents a Point with reference coordinate frame and timestamp\n\
Header header\n\
Point point\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
";
  }

  static const char* value(const  ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.stamp);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetGazeDirectionRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.pointOut);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct GetGazeDirectionResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<monstertruck_msgs::GetGazeDirection> {
  static const char* value() 
  {
    return "ee22875cee6c3a88c49d94bb0d6561c6";
  }

  static const char* value(const monstertruck_msgs::GetGazeDirection&) { return value(); } 
};

template<>
struct DataType<monstertruck_msgs::GetGazeDirection> {
  static const char* value() 
  {
    return "monstertruck_msgs/GetGazeDirection";
  }

  static const char* value(const monstertruck_msgs::GetGazeDirection&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ee22875cee6c3a88c49d94bb0d6561c6";
  }

  static const char* value(const monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "monstertruck_msgs/GetGazeDirection";
  }

  static const char* value(const monstertruck_msgs::GetGazeDirectionRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ee22875cee6c3a88c49d94bb0d6561c6";
  }

  static const char* value(const monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "monstertruck_msgs/GetGazeDirection";
  }

  static const char* value(const monstertruck_msgs::GetGazeDirectionResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // MONSTERTRUCK_MSGS_SERVICE_GETGAZEDIRECTION_H

