/* Auto-generated by genmsg_cpp for file /home/kohlbrecher/argo_repo_rosbuild/stacks/hector/hector_navigation/hector_move_base_msgs/msg/MoveBaseAction.msg */
#ifndef HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEACTION_H
#define HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEACTION_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "hector_move_base_msgs/MoveBaseActionGoal.h"
#include "hector_move_base_msgs/MoveBaseActionResult.h"
#include "hector_move_base_msgs/MoveBaseActionFeedback.h"

namespace hector_move_base_msgs
{
template <class ContainerAllocator>
struct MoveBaseAction_ {
  typedef MoveBaseAction_<ContainerAllocator> Type;

  MoveBaseAction_()
  : action_goal()
  , action_result()
  , action_feedback()
  {
  }

  MoveBaseAction_(const ContainerAllocator& _alloc)
  : action_goal(_alloc)
  , action_result(_alloc)
  , action_feedback(_alloc)
  {
  }

  typedef  ::hector_move_base_msgs::MoveBaseActionGoal_<ContainerAllocator>  _action_goal_type;
   ::hector_move_base_msgs::MoveBaseActionGoal_<ContainerAllocator>  action_goal;

  typedef  ::hector_move_base_msgs::MoveBaseActionResult_<ContainerAllocator>  _action_result_type;
   ::hector_move_base_msgs::MoveBaseActionResult_<ContainerAllocator>  action_result;

  typedef  ::hector_move_base_msgs::MoveBaseActionFeedback_<ContainerAllocator>  _action_feedback_type;
   ::hector_move_base_msgs::MoveBaseActionFeedback_<ContainerAllocator>  action_feedback;


  typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator>  const> ConstPtr;
}; // struct MoveBaseAction
typedef  ::hector_move_base_msgs::MoveBaseAction_<std::allocator<void> > MoveBaseAction;

typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseAction> MoveBaseActionPtr;
typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseAction const> MoveBaseActionConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hector_move_base_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "ef19eb22e9e3d9474f8acbc89c91876b";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xef19eb22e9e3d947ULL;
  static const uint64_t static_value2 = 0x4f8acbc89c91876bULL;
};

template<class ContainerAllocator>
struct DataType< ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hector_move_base_msgs/MoveBaseAction";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> > {
  static const char* value() 
  {
    return "MoveBaseActionGoal action_goal\n\
MoveBaseActionResult action_result\n\
MoveBaseActionFeedback action_feedback\n\
\n\
================================================================================\n\
MSG: hector_move_base_msgs/MoveBaseActionGoal\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
MoveBaseGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: hector_move_base_msgs/MoveBaseGoal\n\
geometry_msgs/PoseStamped target_pose\n\
float32 speed\n\
float32 distance\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: hector_move_base_msgs/MoveBaseActionResult\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
MoveBaseResult result\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalStatus\n\
GoalID goal_id\n\
uint8 status\n\
uint8 PENDING         = 0   # The goal has yet to be processed by the action server\n\
uint8 ACTIVE          = 1   # The goal is currently being processed by the action server\n\
uint8 PREEMPTED       = 2   # The goal received a cancel request after it started executing\n\
                            #   and has since completed its execution (Terminal State)\n\
uint8 SUCCEEDED       = 3   # The goal was achieved successfully by the action server (Terminal State)\n\
uint8 ABORTED         = 4   # The goal was aborted during execution by the action server due\n\
                            #    to some failure (Terminal State)\n\
uint8 REJECTED        = 5   # The goal was rejected by the action server without being processed,\n\
                            #    because the goal was unattainable or invalid (Terminal State)\n\
uint8 PREEMPTING      = 6   # The goal received a cancel request after it started executing\n\
                            #    and has not yet completed execution\n\
uint8 RECALLING       = 7   # The goal received a cancel request before it started executing,\n\
                            #    but the action server has not yet confirmed that the goal is canceled\n\
uint8 RECALLED        = 8   # The goal received a cancel request before it started executing\n\
                            #    and was successfully cancelled (Terminal State)\n\
uint8 LOST            = 9   # An action client can determine that a goal is LOST. This should not be\n\
                            #    sent over the wire by an action server\n\
\n\
#Allow for the user to associate a string with GoalStatus for debugging\n\
string text\n\
\n\
\n\
================================================================================\n\
MSG: hector_move_base_msgs/MoveBaseResult\n\
# empty\n\
\n\
================================================================================\n\
MSG: hector_move_base_msgs/MoveBaseActionFeedback\n\
Header header\n\
actionlib_msgs/GoalStatus status\n\
MoveBaseFeedback feedback\n\
\n\
================================================================================\n\
MSG: hector_move_base_msgs/MoveBaseFeedback\n\
# empty\n\
\n\
";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.action_goal);
    stream.next(m.action_result);
    stream.next(m.action_feedback);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MoveBaseAction_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hector_move_base_msgs::MoveBaseAction_<ContainerAllocator> & v) 
  {
    s << indent << "action_goal: ";
s << std::endl;
    Printer< ::hector_move_base_msgs::MoveBaseActionGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.action_goal);
    s << indent << "action_result: ";
s << std::endl;
    Printer< ::hector_move_base_msgs::MoveBaseActionResult_<ContainerAllocator> >::stream(s, indent + "  ", v.action_result);
    s << indent << "action_feedback: ";
s << std::endl;
    Printer< ::hector_move_base_msgs::MoveBaseActionFeedback_<ContainerAllocator> >::stream(s, indent + "  ", v.action_feedback);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEACTION_H

