/* Auto-generated by genmsg_cpp for file /home/kohlbrecher/argo_repo_rosbuild/stacks/hector/hector_navigation/hector_move_base_msgs/msg/MoveBaseActionExplore.msg */
#ifndef HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEACTIONEXPLORE_H
#define HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEACTIONEXPLORE_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"
#include "actionlib_msgs/GoalID.h"
#include "hector_move_base_msgs/MoveBaseExplore.h"

namespace hector_move_base_msgs
{
template <class ContainerAllocator>
struct MoveBaseActionExplore_ {
  typedef MoveBaseActionExplore_<ContainerAllocator> Type;

  MoveBaseActionExplore_()
  : header()
  , goal_id()
  , goal()
  {
  }

  MoveBaseActionExplore_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , goal_id(_alloc)
  , goal(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
   ::actionlib_msgs::GoalID_<ContainerAllocator>  goal_id;

  typedef  ::hector_move_base_msgs::MoveBaseExplore_<ContainerAllocator>  _goal_type;
   ::hector_move_base_msgs::MoveBaseExplore_<ContainerAllocator>  goal;


  typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator>  const> ConstPtr;
}; // struct MoveBaseActionExplore
typedef  ::hector_move_base_msgs::MoveBaseActionExplore_<std::allocator<void> > MoveBaseActionExplore;

typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseActionExplore> MoveBaseActionExplorePtr;
typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseActionExplore const> MoveBaseActionExploreConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hector_move_base_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9f099efa6d81450c557f59f9dfac4454";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9f099efa6d81450cULL;
  static const uint64_t static_value2 = 0x557f59f9dfac4454ULL;
};

template<class ContainerAllocator>
struct DataType< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hector_move_base_msgs/MoveBaseActionExplore";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
actionlib_msgs/GoalID goal_id\n\
MoveBaseExplore goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: hector_move_base_msgs/MoveBaseExplore\n\
float32 speed\n\
\n\
";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.goal_id);
    stream.next(m.goal);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MoveBaseActionExplore_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hector_move_base_msgs::MoveBaseActionExplore_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
s << std::endl;
    Printer< ::hector_move_base_msgs::MoveBaseExplore_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEACTIONEXPLORE_H

