/* Auto-generated by genmsg_cpp for file /home/kohlbrecher/argo_repo_rosbuild/stacks/hector/hector_navigation/hector_move_base_msgs/msg/MoveBaseGoal.msg */
#ifndef HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEGOAL_H
#define HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEGOAL_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "geometry_msgs/PoseStamped.h"

namespace hector_move_base_msgs
{
template <class ContainerAllocator>
struct MoveBaseGoal_ {
  typedef MoveBaseGoal_<ContainerAllocator> Type;

  MoveBaseGoal_()
  : target_pose()
  , speed(0.0)
  , distance(0.0)
  {
  }

  MoveBaseGoal_(const ContainerAllocator& _alloc)
  : target_pose(_alloc)
  , speed(0.0)
  , distance(0.0)
  {
  }

  typedef  ::geometry_msgs::PoseStamped_<ContainerAllocator>  _target_pose_type;
   ::geometry_msgs::PoseStamped_<ContainerAllocator>  target_pose;

  typedef float _speed_type;
  float speed;

  typedef float _distance_type;
  float distance;


  typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator>  const> ConstPtr;
}; // struct MoveBaseGoal
typedef  ::hector_move_base_msgs::MoveBaseGoal_<std::allocator<void> > MoveBaseGoal;

typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseGoal> MoveBaseGoalPtr;
typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseGoal const> MoveBaseGoalConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hector_move_base_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "f7d11262450941e69b2cd666bccfd015";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xf7d11262450941e6ULL;
  static const uint64_t static_value2 = 0x9b2cd666bccfd015ULL;
};

template<class ContainerAllocator>
struct DataType< ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hector_move_base_msgs/MoveBaseGoal";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> > {
  static const char* value() 
  {
    return "geometry_msgs/PoseStamped target_pose\n\
float32 speed\n\
float32 distance\n\
================================================================================\n\
MSG: geometry_msgs/PoseStamped\n\
# A Pose with reference coordinate frame and timestamp\n\
Header header\n\
Pose pose\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> &) { return value(); } 
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.target_pose);
    stream.next(m.speed);
    stream.next(m.distance);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MoveBaseGoal_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hector_move_base_msgs::MoveBaseGoal_<ContainerAllocator> & v) 
  {
    s << indent << "target_pose: ";
s << std::endl;
    Printer< ::geometry_msgs::PoseStamped_<ContainerAllocator> >::stream(s, indent + "  ", v.target_pose);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};


} // namespace message_operations
} // namespace ros

#endif // HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEGOAL_H

