/* Auto-generated by genmsg_cpp for file /home/kohlbrecher/argo_repo_rosbuild/stacks/hector/hector_navigation/hector_move_base_msgs/msg/MoveBaseFeedback.msg */
#ifndef HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEFEEDBACK_H
#define HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEFEEDBACK_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace hector_move_base_msgs
{
template <class ContainerAllocator>
struct MoveBaseFeedback_ {
  typedef MoveBaseFeedback_<ContainerAllocator> Type;

  MoveBaseFeedback_()
  {
  }

  MoveBaseFeedback_(const ContainerAllocator& _alloc)
  {
  }


  typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator>  const> ConstPtr;
}; // struct MoveBaseFeedback
typedef  ::hector_move_base_msgs::MoveBaseFeedback_<std::allocator<void> > MoveBaseFeedback;

typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseFeedback> MoveBaseFeedbackPtr;
typedef boost::shared_ptr< ::hector_move_base_msgs::MoveBaseFeedback const> MoveBaseFeedbackConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hector_move_base_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hector_move_base_msgs/MoveBaseFeedback";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> > {
  static const char* value() 
  {
    return "# empty\n\
\n\
";
  }

  static const char* value(const  ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct MoveBaseFeedback_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hector_move_base_msgs::MoveBaseFeedback_<ContainerAllocator> & v) 
  {
  }
};


} // namespace message_operations
} // namespace ros

#endif // HECTOR_MOVE_BASE_MSGS_MESSAGE_MOVEBASEFEEDBACK_H

